name: Publish Wheel
on:
  workflow_call:
jobs:
  publish-wheel:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install twine
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
      - uses: actions/download-artifact@v3
        with:
          name: feathub-wheel
          path: ./wheels
      - name: Upload Feathub package
        run: |
          twine upload --username=${{ secrets.PYPI_REPOSITORY_USERNAME }} --password=${{ secrets.PYPI_REPOSITORY_PASSWORD }} wheels/*
